# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-04 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mas_app', '0003_auto_20221104_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
    ]
