# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-05 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mas_app', '0009_auto_20221105_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicines',
            new_name='Medicine',
        ),
    ]
